### ISSUE TITLE
CV32E40P User Manual: specification of privlv CSR

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/core-v-docs#130]
### Type
Issues with this CSR as documented:
* `privlv` is not part of the RISC-V ISA so it needs to be in a "custom" address space.
* The CSR is located at 0xC10, which is "standard read-only" space.
* The "Current Priviledge Level" field contains lots of info that will never relate to CV32E40P.

### Location of Issue
1. RTD URL: https://core-v-docs-verif-strat.readthedocs.io/projects/cv32e40p_um/en/latest/control_status_registers.html#privilege-level-privlv
2. core-v-docs Git Hash:  609007a

**Comment by Silabs-ArjanB** [comment]
The https://github.com/openhwgroup/core-v-docs/pull/106 pull request was supposed to fix the CSR address part (but obviously the actual address was not updated). I will issue a new pull request to update the CSR address (same hold for UHARTID, PRIVLV, HWLOOP*, FPREC)

**Comment by Silabs-ArjanB** [comment]
Justification for this custom CSR can be found in https://github.com/openhwgroup/cv32e40p/issues/381
