### ISSUE TITLE
misa return value

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/core-v-docs#133]
### Note
I'm not sure if this is an RTL bug or a documentation bug, but I've already filed a couple of documentation bugs, so I'll repeat that here.  If this should be an RTL, issue, I can re-create it there.

### Type
Issues with this CSR as documented:
* `misa` is documented to have a reset value of 0x0.
* Actual reset value is 0x40801104.
* This is actually what you'd expect from an RV32IMCX machine.
* Its not clear if CV32E40P should report support for non-standard instructions when PULP=0.

### Location of Issue
1. RTD URL: https://core-v-docs-verif-strat.readthedocs.io/projects/cv32e40p_um/en/latest/control_status_registers.html?highlight=misa#machine-isa-misa
2. core-v-docs Git Hash:  609007a

**Comment by Silabs-ArjanB** [comment]
This was both a documentation and RTL issue indeed. The documentation has been fixed in https://github.com/openhwgroup/core-v-docs/pull/132. The RTL has been fixed in https://github.com/openhwgroup/cv32e40p/pull/398.

**Comment by Silabs-ArjanB** [comment]
Hi @MikeOpenHWGroup Can this one be closed now? (The corresponding PR has been merged)

**Comment by MikeOpenHWGroup** [comment]
Almost, but not quite.  None of the fields of MISA are R/W.  They are all RO.

**Comment by Silabs-ArjanB** [comment]
This should do it then: https://github.com/openhwgroup/core-v-docs/pull/179

**Comment by Silabs-ArjanB** [comment]
Hi @MikeOpenHWGroup Can this be closed now?

**Comment by MikeOpenHWGroup** [comment]
Indeed.  Closing.
