### ISSUE TITLE
Cause bits in dcsr should be read only

### ISSUE THREAD

**Issue by silabs-oysteink** [openhwgroup/core-v-docs#182]
According to the riscv debug specification v0.13.2, the cause bits ([8:6]) in dcsr should be read only. During debug testing, I found that code executing in debug mode can actually write to these bits, causing a mismatch with the reference model.

**Comment by Silabs-ArjanB** [comment]
Fixed in https://github.com/openhwgroup/core-v-docs/pull/197

**Comment by Silabs-ArjanB** [comment]
Hi @silabs-oysteink , can you please close this one if you agree it has been fixed?
