### ISSUE TITLE
Incomplete discussion of 

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/core-v-docs#183]
The [Time Registers](https://github.com/openhwgroup/core-v-docs/edit/master/cores/cv32e40p/user_manual/source/perf_counters.rst) sub-section of the User Manual reads:
```
Time Registers (``time(h)``)
----------------------------

The user mode ``time(h)`` registers are not implemented. Any access to these
registers will trap. It is recommended that a software trap handler is
implemented to detect access of these CSRs and convert that into access of the
platform-defined ``mtime`` register (if implemented in the platform).
```

A couple of things could be clarified:
1. What type of trap occurs if the time(h) registers are accessed?  That is, what status bits are set, etc.
2. The mtime register is not implemented in CV32E40P so the reference to it here could be removed.

**Comment by Silabs-ArjanB** [comment]
1) Illegal instruction
2) Could be removed indeed, but it is useful info

**Comment by Silabs-ArjanB** [comment]
Fixed with https://github.com/openhwgroup/core-v-docs/pull/187

**Comment by MikeOpenHWGroup** [comment]
Thanks.
