### ISSUE TITLE
FP_FMA instantiation

### ISSUE THREAD

**Issue by EthanZhouxl** [openhwgroup/core-v-docs#253]
Hi
In the RTL code, you integrated your private FMA.
But in the user manual, you mentioned that the FP-FMA is currently only supported through a Synopsys Design Ware instantiation, or a Xilinx block for FPGA targets.
Could you please help confirm which IP should be instantiated? 
Thanks

![image](https://user-images.githubusercontent.com/37069982/43520693-2a8240fe-95c6-11e8-83c1-703903ccca41.png)

**Comment by MikeOpenHWGroup** [comment]
Hi @davideschiavone, @Silabs-ArjanB and @EthanZhouxl.  This issue needs a label.

**Comment by davideschiavone** [comment]
Fixed in #256
