### ISSUE TITLE
Add Illegal conditions for instructions within a HWloop

### ISSUE THREAD

**Issue by davideschiavone** [openhwgroup/core-v-docs#265]
If the core is executing a hardware loop, instructions like:

Uncoditional jumps, conditonal branches, system calls like mret, dret, fences, and wfi are not allowed.

These constraints are alreayd implemented in the RTL. However, they are not in the _HWloop constraints_ Section of the document

https://core-v-docs-verif-strat.readthedocs.io/projects/cv32e40p_um/en/latest/pulp_hw_loop.html#hwloop-specs

**Comment by MikeOpenHWGroup** [comment]
What should happen if the core attempts to execute one of these jumps/branches/syscalls in a HWloop?   Perhaps an illegal instruction exception?

**Comment by davideschiavone** [comment]
Hi @MikeOpenHWGroup , yes!

**Comment by jeremybennett** [comment]
As noted in the PR #261, this affects the compiler teams!

**Comment by davideschiavone** [comment]
Closed by PR #266
