### ISSUE TITLE
The core interface is not updated with the last debug-realted ports

### ISSUE THREAD

**Issue by davideschiavone** [openhwgroup/core-v-docs#267]
The core does not have specifically the newest added ports:

debug_havereset_o
debug_running_o
debug_halted_o

They should also be documented in the debug section of the documentation

**Comment by MikeOpenHWGroup** [comment]
Hi @davideschiavone, the core _does_ have these outputs.

**Comment by Silabs-ArjanB** [comment]
@silabs-PaulZ This has all been documented; could you just review https://github.com/openhwgroup/cv32e40p/pull/564

**Comment by davideschiavone** [comment]
> 
> 
> Hi @davideschiavone, the core _does_ have these outputs.
> 
> I agree that they should be mentioned in both the Core Integration and Debug sections of the User Manual and that this should gate Functional RTL Freeze.

The core "does not" in the documentation I mean :)

**Comment by davideschiavone** [comment]
Thanks @Silabs-ArjanB - we should merge this PR asap

**Comment by davideschiavone** [comment]
Please @silabs-PaulZ , let us know about the revision to close this issue

**Comment by silabs-PaulZ** [comment]
I added review comments in #242 and should be ready to close.

**Comment by Silabs-ArjanB** [comment]
https://github.com/openhwgroup/core-v-docs/pull/242 has been reviewed and merged now

**Comment by davideschiavone** [comment]
Thanks @Silabs-ArjanB and @silabs-PaulZ

**Comment by MikeOpenHWGroup** [comment]
It might also be a good idea to update the [instantiation template](https://core-v-docs-verif-strat.readthedocs.io/projects/cv32e40p_um/en/latest/integration.html#instantiation-template) of the Core Integration chapter.

**Comment by Silabs-ArjanB** [comment]
? That is a good idea and that is why we did it

**Comment by MikeOpenHWGroup** [comment]
I must have had a stale view of the User Manual on RTD.   Looks fine now.
