### ISSUE TITLE
Cycle counts for CSR instructions are not properly documented

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/core-v-docs#274]
The cycle counts for CSR instructions are not properly documented:

![image](https://user-images.githubusercontent.com/40633348/99949707-c5576b00-2d7b-11eb-973b-70a0b1c35542.png)

In reality some CSR accesses will trigger a pipeline flush and will therefore take more cycles.

**Comment by davideschiavone** [comment]
This should be closed now #275 @Silabs-ArjanB
