### ISSUE TITLE
 core-v-docs/cores/cv32e40p/user_manual/origin/ folder is deprecated

### ISSUE THREAD

**Issue by davideschiavone** [openhwgroup/core-v-docs#276]
The folder and its content at 

core-v-docs/cores/cv32e40p/user_manual/origin/

contains two user_manual files that are not used anywhere (if I am not wrong). They should be removed.

**Comment by MikeOpenHWGroup** [comment]
Indeed.  These files were kept in the early days of our switch to Restructured Text (rst) and ReadTheDocs.  I agree these can be removed altogether now as the User Manual is now both comprehensive and well organized (you people are amazing!).

Do you need me to actually delete these files?

**Comment by davideschiavone** [comment]
No I can do it thankes :) just needed to be confirmed @MikeOpenHWGroup
