### ISSUE TITLE
How to handle new interrupt inputs

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/core-v-docs#31]
The CV32E40P has a number of new interrupt inputs:
![image](https://user-images.githubusercontent.com/55248931/74286392-ac526180-4cf5-11ea-81cf-df5f71613888.png)
Is it safe to tie all these off to 'b0 until such time as the testbenches can do something interesting with them?

Related question: when/where will the function of these new inputs be documented?

**Comment by Silabs-ArjanB** [comment]
The testbench could check the following:

- relative priorities for all these interrupts
- interrupt pending bits for all the interrupts
- interrupt enable bits for all the interrupts
- use of correct mtvec or mtvecx (target address and vectoring mode)
- impact on exception cause

**Comment by MikeOpenHWGroup** [comment]
Hi @Silabs-ArjanB, these are all good points.  The place to record these is in the [Verification Plan](https://github.com/openhwgroup/core-v-docs/tree/master/verif/CV32E40P/VerificationPlan).  At this point we do not have anyone allocated to verify this Feature and getting one or two Active Contributors started on this is a top priority for me.
