### ISSUE TITLE
spec change - restrict HW loop with only one instruction

### ISSUE THREAD

**Issue by Itaykeidar** [openhwgroup/core-v-docs#32]
need to state in spec that HW loop with only one instruction is restricted

**Comment by davideschiavone** [comment]
This should be fixed now @Silabs-ArjanB

**Comment by Silabs-ArjanB** [comment]
@davideschiavone Agreed that this is fixed in the documentation in https://core-v-docs-verif-strat.readthedocs.io/projects/cv32e40p_um/en/latest/pulp_hw_loop.html. 

This was not my ticket though; @Itaykeidar could you please close this ticket if you agree with the fix?
