### ISSUE TITLE
Hardware loop documentation unclear

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/core-v-docs#33]
Chapter 7 PULP Hardware Loop Extensions of the RI5CY User Manual states:

> HWLoop body must contain at least **3 instructions**

and also

> Note that the minimum loop size is **two instructions** and the last instruction cannot be any jump or branch instruction.

I assume that the following:

> Start address of an HWLoop must be **aligned**

should be:

> Start address of an HWLoop must be **word aligned**

Could you please comment on the minimum loop size and alignment restriction?

**Comment by davideschiavone** [comment]
can it be closed ? @Silabs-ArjanB

**Comment by Silabs-ArjanB** [comment]
Thank you; I close it now
