### ISSUE TITLE
Remove cv32e40p documentation 

### ISSUE THREAD

**Issue by davideschiavone** [openhwgroup/core-v-docs#343]
As the documentation of the core moved to the cv32e40p repository, the one here is deprecated and should be deleted.
Also the project in readthedocs one should be deleted to and the old http link should not be visible anymore.

**Comment by MikeOpenHWGroup** [comment]
1. RTD project for core-v-docs version of the cv32e40p deleted.
2. Pull request #346 pending to remove user_manual from this repo.

**Comment by MikeOpenHWGroup** [comment]
Tried to fix a problem with #346, using #348.  Didn't work as planned, but merged anyway.   This issue can be closed.
