### ISSUE TITLE
Table formatting

### ISSUE THREAD

**Issue by silabs-PaulZ** [openhwgroup/core-v-docs#40]
The table formatting in the Verification Strategy (see https://core-v-docs-verif-strat.readthedocs.io/en/latest/sim_tests.html#virtual-peripherals) is hard to read. The content does not wrap and requires using the scroll bar. The PDF is also not formatted cleanly.

This formatting may possibly be fixed by overriding the theme, as seen in Ibex's conf.py

```
html_static_path = ['_static']

html_context = {
    'css_files' : [
        '_static/theme_overrides.css', # Fix wide tables in RTD theme
        ],
    }
```

**Comment by jm4rtin** [comment]
I think that comes from: https://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html

When you turn this on (for the CV32E40P User Guide) the instruction encoding tables start wrapping all the cells:
![image](https://user-images.githubusercontent.com/20426677/82494551-01e19b80-9aa7-11ea-8f17-9ae8d6978cba.png)

So the solution may not be quite so simple.

**Comment by MikeOpenHWGroup** [comment]
Seems to work for the tables in the VerifStrat, so I pushed it on top of PR #262, so poor @Silabs-ArjanB get to review it.   Thanks for the tip @silabs-PaulZ.

**Comment by MikeOpenHWGroup** [comment]
Marked as resolved.   @silabs-PaulZ can you review and close (once the merge gets done).

**Comment by MikeOpenHWGroup** [comment]
Hi @silabs-PaulZ, can you have an look?  (Yes, I'm in "nag" mode these days...)

**Comment by silabs-PaulZ** [comment]
looks good, thanks
