### ISSUE TITLE
Update Interrupt Documentation on CV32E40P

### ISSUE THREAD

**Issue by davideschiavone** [openhwgroup/core-v-docs#43]
## Update Interrupt Documentation on CV32E40P

Interrupts changed on CV32E40P and they are based on the CLINT spec.
The implementation is based on the Ibex core and it has been extended with 32 extra
fast custom interrupts.

**Comment by Silabs-ArjanB** [comment]
@davideschiavone I actually wrote most of this documentation (including a small change request) last Friday; I will do a pull request for this documentation today; could you please wait with this one until you see my pull request?

**Comment by Silabs-ArjanB** [comment]
@davideschiavone Could you please close this ticket so that we handle all IRQ updates via #50 ?
