### ISSUE TITLE
Inconsistent Requirements numbering across revisions

### ISSUE THREAD

**Issue by MikeOpenHWGroup** [openhwgroup/core-v-docs#538]
The numbering requirements in the **List of Requirements** chapter of various revisions of the OBI specification is not consistent.  For example, in OBI v1.5, Requirement R-7 is expanded into Requirements R-7 and R-8, which increments the Requirement number for all subsequent Requirements.  So, for example, R-8 in OBI v1.2 is R-9 in OBI v1.5.

This situation makes tracking of requirements in verification plans and in testbench code difficult.

Two possible solutions:
1. Cancel R-7 and add new requirements using unused numbers.
2. Edit R-7 to make it hierarchical (e.g. R-7.1..R-7.4).

**Comment by Silabs-ArjanB** [comment]
In our methodology the numbers are not required to be consistent (and are not actually used). If you are actually using the numbers, then you can only do so in combination with the version of the document.
