### ISSUE TITLE
RI5CY: User Manual v4.2-14.5.1 pv.subrotmj.* instruction undefined

### ISSUE THREAD

**Issue by alfredoh1234** [openhwgroup/core-v-docs#82]
There is no description of what the pv.subrotmj.* instruction is. From another document on the web, it seems like it is the "substraction of two 16-bit complex numbers with post rotation by -j" or
* rD[15:0 ] =   rA[31:16] - rB[31:16]
* rD[31:16] = -(rA[15:0 ] - rB[15:0])

Please clarify

**Comment by alfredoh1234** [comment]
Because when writing the verification code it is important to know the expected result, boundary conditions and how to insert cases that will create an expected error to test any exception handling or flags in the CSRs

**Comment by davideschiavone** [comment]
The fix is now in 
https://github.com/openhwgroup/core-v-docs/pull/87

Can you please confirm and give me feedback?

thanks
Davide

**Comment by davideschiavone** [comment]
@alfredoh1234 can you please add comment?

**Comment by alfredoh1234** [comment]
It is better. You can close [issue #82](https://github.com/openhwgroup/core-v-docs/issues/82)
